config/routes.rb
Crowdfunder::Application.routes.draw do
  resources :projects
  resources :pledges, :only => [:new, :create]
  resources :users, except: :index

  resource :session, :only => [:new, :create, :destroy]
  root to: "welcome#index"

end

app/models/pledge.rb
class Pledge < ActiveRecord::Base
  belongs_to :user
  belongs_to :project
  attr_accessible :amount
  validates_presence_of :user
  validates_presence_of :project
  validates_numericality_of :amount, :greater_than => 0
end

app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :user
  has_many :pledges
  attr_accessible :description, :goal, :teaser, :title
end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!
  attr_accessible :first_name, :last_name, :email, :password
  has_many :pledges
  has_many :projects
  validates_presence_of :email
  validates_presence_of :password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pledges_controller.rb
class PledgesController < ApplicationController
  def new
    @pledge = Pledge.new
  end

  def create
    @pledge = Pledge.new(params[:plegde])
    if @pledge.save
      redirect_to :back, :notice => "Thanks for your pledge!"

    else
      flash[:alert] = "Try again"
      render :new
  end
end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
    @projects = Project.all
  end

  def show
    @project = Project.find(params[:id])
  end

  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = login(params[:email], params[:password])
    if user
      redirect_to root_path, :notice => "Logged in!"
    else
      flash.now.alert = "Invalid"
      render :new
    end
  end

  def destroy
    logout
    redirect_to root_path, :notice => "Bye"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      auto_login(@user)
      redirect_to root_path, :notice => "Account created"

    else
      flash[:alert] = "Try again"
      render :new
    end
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pledges_helper.rb
module PledgesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Crowdfunder</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container">
        <a class="brand" href="/">CrowdFunder</a>
        <div class="nav-collapse collapse">
          <ul class="nav">
            <li <%= yield(:li_class_hm)%>>
              <%= link_to "Home", :root %>
            </li>
            <li <%= yield(:li_class_pj)%>>
            <%= link_to 'Projects', :projects %>
            </li>
            <% if current_user %>
              <li <%= yield(:li_class_user)%>>
              <%= link_to current_user.first_name, user_path(current_user.id)%></li>
              <li> <%= link_to "Logout", session_path("current"), :method => :delete  %></li>
            <% else %>
                <li <%= yield(:li_class_sign)%>>
                  <%= link_to "Sign Up", new_user_path %></li>
                <li <%= yield(:li_class_log)%>>
                  <%= link_to "Login", new_session_path%></li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
    </div>
  </div>
  <div class="page">
  <% if flash[:notice] %>
    <p class="alert"><%=flash[:notice] %></p>
  <% end %>
  <% if flash[:alert] %>
    <p class="alert"><%=flash[:alert] %></p>
  <% end %>
  <%= yield %>

</body>
</html>

app/views/pledges/new.html.erb
<h1>Pledge dawg!</h1>
<div class="pledge-form">
<%= form_for @pledge do |f| %>

  <% if @pledge.errors.any? %>
    <div id="error_explanation">
      <ul>
        <% @pledge.errors.full_messages.each do |msg| %>
        <li> <%= msg %> </li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :project_id %>
    <%= f.text_field :project_id %>
  </div>

  <div class="field">
    <%= f.label :user_id %>
    <%= f.text_field :user_id %>
  </div>

  <div class="field">
    <%= f.label :amount %>
    <%= f.number_field :amount %>
  </div>

  <div class = "action">
    <%= f.submit "Pledge" %>
  </div>

  <% end %>
</div>

app/views/projects/create.html.erb
<h1>Projects#create</h1>
<p>Find me in app/views/projects/create.html.erb</p>

app/views/projects/destroy.html.erb
<h1>Projects#destroy</h1>
<p>Find me in app/views/projects/destroy.html.erb</p>

app/views/projects/edit.html.erb
<h1>Projects#edit</h1>
<p>Find me in app/views/projects/edit.html.erb</p>

app/views/projects/index.html.erb
<% provide(:li_class_pj, "class=active") %>
<h1>Listing projects</h1>
  <div class="container">
    <% @projects.each do |project| %>
    <div class="projectindex">
      <p>
        <strong> <%= link_to project.title, project_path(project.id)%></strong><br>
        <em> Project by: <%= project.user_id %> </em><br>
        <%= project.teaser %><br>
      </p>
    </div>
      <% end %>
  </div>

app/views/projects/new.html.erb
<h1>Projects#new</h1>
<p>Find me in app/views/projects/new.html.erb</p>

app/views/projects/show.html.erb
<% provide(:li_class_pj, "class=active") %>
<h1>  <strong> <%= @project.title %></strong> </h1>
<div class="container">
  <div class="projectindex">
    <p>
      <em> Project by user: <%= @project.user_id %> </em><br>
      <%= @project.description %><br>
      Our goal! $<%= @project.goal %><br>
      We've been funding since <%= @project.created_at %>
    </p>
    <button> <%= link_to "Pledge", new_pledge_path %> </button>
  </div>
</div>

app/views/projects/update.html.erb
<h1>Projects#update</h1>
<p>Find me in app/views/projects/update.html.erb</p>

app/views/users/new.html.erb
<% provide(:li_class_sign, "class=active") %>
<h1>Sign up dawg!</h1>
<div class="signup-form">
<%= form_for @user do |f| %>

  <% if @user.errors.any? %>
    <div id="error_explanation">
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
        <li> <%= msg %> </li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %>
    <%= f.email_field :email %>
  </div>

  <div class="field">
    <%= f.label :first_name %>
    <%= f.text_field :first_name %>
  </div>

  <div class="field">
    <%= f.label :last_name %>
    <%= f.text_field :last_name %>
  </div>

  <div class="field">
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>

  <div class = "action">
    <%= f.submit "Create Account" %>
  </div>

  <% end %>
</div>

app/views/users/show.html.erb
<% provide(:li_class_user, "class=active") %>
<h1> User profile </h1>
Right now set up as user#show. Possibly change to user#edit?

THINK ABOUT IT.

app/views/welcome/index.html.erb
<% provide(:li_class_hm, "class=active") %>
<h1> welcome </h1>